@startuml
!theme materia

skin rose

title Diagrama de Classes - Klav-Tasks

package com.klav.users {

  class Assinatura {
    -{field} Int Id
    -{field} String Nome
    -{field} Double Valor
    -{field} Int NumeroMaximoProjetos
    -{field} Int NumeroMaximoTarefas
    -{field} Int NumeroMaximoSubTarefas
  }
  
  class Usuario {
    -{field} Long Id
    -{field} String Nome
    -{field} String Email
    -{field} String ValorHora
    -{field} Date DataCadastro
  }
}

package com.klav.tasks {

  enum Prioridade {
    BAIXA
    MEDIA
    ALTA
    URGENTE
  }
  
  class Projeto {
    -{field} Long Id
    -{field} String UUID
    -{field} String Nome
    -{field} String Descricao
    -{field} Date DataCadastro
    -{field} Date DataInicial
    -{field} Date DataFinal
    -{field} Double ValorVenda
    +{method} Double CustoTotal
    +{method} Int NumeroTotalTarefas
  }
  
  class Tarefa {
    -{field} Long Id
    -{field} String Nome
    -{field} String Descricao
    -{field} Date DataCadastro
    -{field} Date DataInicial
    -{field} Date DataFinal
    +{method} Double CustoTotal
    +{method} Int NumeroTotalSubTarefas
  }

  class SubTarefa {
    -{field} Long Id
    -{field} String Nome
    -{field} String Descricao
    -{field} Date DataCadastro
    -{field} Date DataInicial
    -{field} Date DataFinal
    -{field} Int NumeroHoras
    -{field} Double ValorHoraUsuario
    +{method} CustoSubTarefa
  }
  
  class UsuarioProjeto
}

Assinatura "1" --* "many" Usuario
Usuario "1" -left-* "many" Projeto
Usuario "1" --* "many" UsuarioProjeto
Projeto "1" --* "many" UsuarioProjeto
Projeto "1" --* "many" Tarefa
Tarefa "1" --* "many" SubTarefa
Usuario "1" --* "many" SubTarefa
Usuario "1" --* "many" SubTarefa
Prioridade "1" -right- "1" Projeto
Prioridade "1" -- "1" Tarefa
Prioridade "1" -- "1" SubTarefa
@enduml
