@startuml
!theme materia

skin rose

title Diagrama de Classes - Klav-Tasks

class Assinatura {
  {field} Int IdAssinatura
  {field} String NomeAssinatura
  {field} Double ValorAssinatura
  {field} Int NumeroMaximoProjetos
  {field} Int NumeroMaximoTarefas
  {field} Int NumeroMaximoSubTarefas
}

class Usuario {
  {field} UUID IdUsuario
  {field} String NomeUsuario
  {field} String EmailUsuario
  {field} String ValorHoraUsuario
  {field} Date DataCadastro
}

class Projeto {
  {field} UUID IdProjeto
  {field} String NomeProjeto
  {field} Double ValorVendaProjeto
  {field} Date DataCadastro
  {field} Date DataInicial
  {field} Date DataFinal
  {method} Double CustoProjeto
  {method} Int NumeroTarefas
}

class Tarefa {
  {field} UUID IdTarefa
  {field} String NomeTarefa
  {field} Date DataCadastro
  {field} Date DataInicial
  {field} Date DataFinal
  {method} Double CustoTarefa
}

class SubTarefa {
  {field} UUID IdSubTarefa
  {field} String NomeSubTarefa
  {field} Date DataCadastro
  {field} Date DataInicial
  {field} Date DataFinal
  {field} Int NumeroHoras
  {field} Double ValorHoraUsuario
  {method} CustoSubTarefa
}

Assinatura "1" -left-* "many" Usuario
Usuario "1" -left-* "many" Projeto
Projeto "1" --* "many" Tarefa
Tarefa "1" -right-* "many" SubTarefa
Usuario "1" --* "many" SubTarefa
@enduml
